---
title: "VSU Risk Assessment 2026"
format: 
  dashboard:
    orientation: columns
    theme: 
        light: simplex
        dark: darkly
logo: img/vsu-logo.svg
---

```{r}
#| label: load-packages
library(tidyverse)
library(readxl)
library(janitor)
library(scales)
library(lessR)
library(plotly)
library(tidytext)
library(ggwordcloud)

options(plotly_suggest = FALSE)

```

```{r}
#| label: data-management
## setting workind environment
setwd(here::here("risk-assessment"))

## load data
risk_dta <- read_excel("data/risk-assessment.xlsx") |> 
    clean_names()
```


## Column - Risk identified across department {width="45%"}

### Value boxed {height="25%"}

```{r}
## very high risk department
dept_risk_dta <- 
    risk_dta |> 
    count(department, risk_rating) |> 
    filter(risk_rating %in% c("Very High", "High")) |> 
    na.omit()

dept_name_risk_dta <- 
    risk_dta |> 
    count(department, risk_rating) |> 
    filter(risk_rating %in% c("Very High")) |> 
    pull(department)

category_most_risk_dta <- 
    risk_dta |> 
    count(risk_category, risk_rating) |> 
    group_by(risk_category) |> 
    mutate(pct = n / sum(n)) |> 
    ungroup() |> 
    filter(risk_rating == "Very High") |> 
    mutate(risk_category = if_else(str_detect(risk_category, "Information"), "Information/ Cybersecurity", risk_category)) |> 
    slice_max(order_by = pct, n = 1) |> 
    pull(risk_category) 

```

::: {.valuebox icon="search" color="danger"}
**Total risk identified**

`{r} nrow(risk_dta)`

:::

::: {.valuebox icon="building-fill-exclamation" color="warning"}
**High risks department**

`{r} nrow(dept_risk_dta)`

:::

::: {.valuebox icon="pc-display-horizontal" color="info"}
**Top risk**

`{r} paste(category_most_risk_dta)`
:::




### Row - Risk identified {height="75%"}

```{r}
#| label: risk identified
#| title: Departmental Risk Distribution 
#| fig-width: 5

p <- risk_dta |> 
  count(department, risk_rating) |> 
  na.omit() |> 
  mutate(risk_rating = factor(risk_rating, 
                              levels = c("Low", "Tolerable", "High", "Very High"))) |>
  group_by(department) |> 
  mutate(pct = n / sum(n)) |> 
  ungroup() |> 
  mutate(risk_rating = forcats::fct_rev(risk_rating)) |>
  # build custom hover label
  mutate(hover_lab = paste0("Department: ", department,
                            "\nRating: ", risk_rating,
                            "\nCount: ", n,
                            "\nPercent: ", round(pct*100, 2), "%")) |>
  ggplot(aes(pct, department, fill = risk_rating, text = hover_lab)) +
  geom_col(width = 0.7) +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("#d62828", "#fa9324", "#f7f96bee", "#06d6a0")) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(
    y = NULL,
    x = NULL,
    fill = NULL
  ) +
  theme_light() +
  theme(
    axis.text = element_text(size = 9),
    legend.position = "bottom",
    legend.text = element_text(size = 11),
    legend.title = element_text(size = 11)
  )

ggplotly(p, tooltip = "text")
```






## Columns - Risk category and rating {width="55%"}

### Row - Risk breakdown {height="50%"}

```{r}
#| label: risk description
#| title: Risk descriptions
#| warning: false
#| message: false


p_risk_dec <- risk_dec_dta <- 
    risk_dta |> 
    select(risk_description) |> 
    unnest_tokens(word, risk_description) |> 
    anti_join(stop_words) |> 
    count(word, sort = TRUE) |> 
    filter(n > 1)

set.seed(20260413)
ggwordcloud(risk_dec_dta$word, risk_dec_dta$n,  min.freq = 2, scale = c(6, 0.6))
# ggsave(plot = p_risk_dec, filename = "img/risk_dec.jpeg", width = 10, height = 8, dpi = 300)
```


### Row - Risk category {.tabset height="50%"}

```{r}
#| label: risk rating all
#| title: Overall Risk Level Profile
#| warning: false
#| message: false

risk_dta |> 
  count(risk_rating) |> 
  mutate(pct = n / sum(n),
         pct_lab = str_c(risk_rating, ": ", round(pct * 100, 2), "%"),
         hover_lab = str_c("Category: ", risk_rating,
                           "<br>Count: ", n,
                           "<br>Percent: ", round(pct * 100, 2), "%")) |>
  plot_ly(labels = ~risk_rating, values = ~pct, type = "pie",
          textinfo = "label+percent",      
          textposition = "outside",
          hoverinfo = "text",              
          hovertext = ~hover_lab,          
          marker = list(colors = c("#fa9324", "#06d6a0", "#f7f96bee", "#d62828")),
          hole = 0.5) |>
  layout(title = NULL,
         showlegend = FALSE)

```

```{r}
#| label: risk category
#| title: Risk Categories by Severity 

P_risk_category <- 
    risk_dta |> 
    count(risk_category, risk_rating) |> 
    mutate(risk_rating = factor(risk_rating, levels = c("Low", "Tolerable", "High", "Very High"))) |>
    group_by(risk_category) |> 
    mutate(pct = n / sum(n)) |> 
    ungroup() |> 
    mutate(risk_rating = fct_rev(risk_rating)) |> 
    mutate(hover_lab = paste0("Category: ", risk_category,
                            "\nRating: ", risk_rating,
                            "\nCount: ", n,
                            "\nPercent: ", round(pct*100, 2), "%")) |> 
    ggplot(aes(pct, risk_category, fill = risk_rating, text = hover_lab)) +
    geom_col(width = 0.7) +
    scale_x_continuous(labels = percent_format()) +
    scale_fill_manual(values = c("#d62828", "#fa9324", "#f7f96bee", "#06d6a0")) +
    guides(fill = guide_legend(reverse = TRUE)) +
    labs(
        y = NULL,
        x = NULL,
        fill = NULL
    ) +
    theme_light() +
    theme(
        axis.text = element_text(size = 10),
        legend.position = "bottom",
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 10)
    )

ggplotly(P_risk_category, tooltip = "text")
```



